displayName=Instant Inventory
author=Elg
support=https://github.com/elgbar/instant-inventory/issues
description=Perform inventory actions instantly
tags=inventory,qol,improvement,overlay,instant,client,drop,clean,herb,quality,of,life,item,items,equip,special,attack
plugins=no.elg.ii.InstantInventoryPlugin
build=standard
version=1.6.0